<template>
  <div>
    <h1>
      This is a proof of concept on strict CSP without cookies
    </h1>
    <h3>
      This application is under 'strict-dynamic' policy with nonces
    </h3>
    <h3>
      Navigate to the following pages to analyze behaviour:
    </h3>
    <ol>
      <li>
        <NuxtLink to="external-script">
          A page that loads an external script
        </NuxtLink>
      </li>
      <li>
        <NuxtLink to="external-style">
          A page that loads an external stylesheet
        </NuxtLink>
      </li>
      <li>
        <NuxtLink to="bootstrap">
          A page that loads Bootstrap external ressources
        </NuxtLink>
      </li>
      <li>
        <NuxtLink to="inline-injected-script">
          A page that injects an inline script generated by an API route
        </NuxtLink>
      </li>
      <li>
        <NuxtLink to="inline-injected-style">
          A page that injects an inline stylesheet generated by an API route
        </NuxtLink>
      </li>
      <li>
        <NuxtLink to="image">
          A page that uses the NuxtImg component
        </NuxtLink>
      </li>
      <li>
        <NuxtLink to="image-preload">
          A page that uses NuxtImg with preload
        </NuxtLink>
      </li>
    </ol>
    <br>
    <NuxtLink to="proposal">Proposal</NuxtLink>
    <br>
    <h4>
      Some generic comments about strict CSP
    </h4>
    <ul>
      <li>
        Issues with CSP usually arise because of a bad setting of CSP policies. The first thing to do is to check your policies.
      </li>
      <li>
        CSP is hard, because the rules depend on whether you are loading a script, a style, an image, etc. And also because the rules are not the same depending on the type of resource.
      </li>
      <li>
        Yes, the syntax is horrendous and misleading. One example is the 'nonce' syntax: it applies to all resources for 'script-src', but only to inlined resources for 'style-src'. Oh, and even for 'script-src', this is valid only if you have 'strict-dynamic', otherwise no this is not true anymore. Who knows why.
      </li>
      <li>
        Don't try to over-engineer the rules or bypass them. If you need to introduce a very complex setup, you are probably not fixing the right problem.
      </li>
      <li>
        Understanding what type of ressource is being loaded is the first step towards a solution. With high-level frameworks such as Nuxt, it is often not obvious who is loading what
      </li>
      <li>
        CSP rules per route are useless in Nuxt. This is because the rules are provided by the server via its reponse headers. In a Nuxt application, you will only hit the server upon first load, and any subsequent navigation will be done client-side and not hit the server again. So if you design specific per-route policies, you will never receive them after the first load.
      </li>
      <li>
        Bottom line, don't design per-route CSP. Make sure you have one single set of rules that apply to all of your application, regardless of the route being navigated to.
      </li>
      <li>
        These notes only cover SSR. SSG/SPA is a completely different story because in that case we won't have a server with a Nitro runtime, so we cannot modify headers and inject nonces. The solution is completely different and involves the http 'meta' tag and SHA hashes.
      </li>
      <li>
        If you cannot achieve CSP, don't use CSP. CSP is not mandatory.
      </li>
    </ul>
  </div>
</template>
